export const WAITLIST_CREATE_REQUEST = 'WAITLIST_CREATE_REQUEST';
export const WAITLIST_CREATE_SUCCESS = 'WAITLIST_CREATE_SUCCESS';
export const WAITLIST_CREATE_FAILED = 'WAITLIST_CREATE_FAILED';
export const WAITLIST_CREATE_RESET = 'WAITLIST_CREATE_RESET';


export const WAITLIST_UPDATE_REQUEST = 'WAITLIST_UPDATE_REQUEST';
export const WAITLIST_UPDATE_SUCCESS = 'WAITLIST_UPDATE_SUCCESS';
export const WAITLIST_UPDATE_FAILED = 'WAITLIST_UPDATE_FAILED';
export const WAITLIST_UPDATE_RESET = 'WAITLIST_UPDATE_RESET';