# Generated by Django 4.2 on 2024-08-26 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("graph", "0001_initial"),
        ("stage", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entity", "0002_initial"),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_interview",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graph_interviews",
                to="graph.graph",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviewer_interviews",
                to="entity.interviewer",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node_interviews",
                to="graph.node",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_interviews",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stage_interviewes",
                to="stage.stage",
            ),
        ),
    ]
