# Generated by Django 4.2 on 2024-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("cancelled", "Cancelled"),
                    ("error", "error"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
