# Generated by Django 4.2 on 2024-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0003_alter_interview_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
