# Generated by Django 4.2 on 2024-10-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import susanoo.entity.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0002_alter_stage_type_stagev2"),
        ("organization", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entity", "0002_initial"),
        ("graph", "0002_alter_node_memory_level_alter_node_type_prompt_and_more"),
        ("interview", "0004_alter_interview_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("job", "Job"), ("pitch", "Pitch")],
                        default="job",
                        max_length=20,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Start"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="End"),
                ),
                (
                    "started_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Started"),
                ),
                (
                    "ended_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ended"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=susanoo.entity.models.PathAndRename("resumes/"),
                        verbose_name="Resume",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Metadata"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_interviews_v2",
                        to="entity.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_interview_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_interviews_v2",
                        to="graph.graphv2",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviewer_interviews_v2",
                        to="entity.interviewer",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="node_interviews_v2",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_interviews_v2",
                        to="organization.organization",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_interviewes_v2",
                        to="stage.stage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
