# Generated by Django 4.2 on 2024-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0005_interviewv2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("dsa", "DSA"), ("job", "Job"), ("pitch", "Pitch")],
                default="job",
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="interviewv2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("dsa", "DSA"), ("job", "Job"), ("pitch", "Pitch")],
                default="job",
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
