# Generated by Django 4.2 on 2024-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0003_stagev2_module_stagev2_required_alter_stage_type_and_more"),
        ("interview", "0007_alter_interviewv2_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewv2",
            name="stages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="stage_interviews",
                to="stage.stagev2",
            ),
        ),
    ]
