# Generated by Django 4.2 on 2024-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0008_interviewv2_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                    ("expired", "Expired"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="interviewv2",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                    ("expired", "Expired"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
