# Generated by Django 4.2 on 2024-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0009_alter_interview_status_alter_interviewv2_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewv2",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="Config"),
        ),
    ]
