# Generated by Django 4.2 on 2025-04-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0009_alter_stagev2_code"),
        ("job", "0003_job_title"),
        ("interview", "0010_interviewv2_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewv2",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_interviews_v2",
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="interviewv2",
            name="stages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="stage_interviews_v2",
                to="stage.stagev2",
            ),
        ),
    ]
