# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KNOWLEDGE", "KNOWLEDGE"),
                            ("PROBLEM_SOLVING", "PROBLEM_SOLVING"),
                            ("ALIGNMENT_WITH_JOB", "ALIGNMENT_WITH_JOB"),
                            ("COMMUNICATION_SKILLS", "COMMUNICATION_SKILLS"),
                            ("OVERALL", "OVERALL"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlatformFeedback",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
