# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformfeedback",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_feedback",
                to="interview.interview",
            ),
        ),
        migrations.AddField(
            model_name="interviewfeedback",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="interview.interview",
            ),
        ),
    ]
