# Generated by Django 4.2 on 2024-11-09 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0007_alter_interviewv2_stage"),
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewfeedback",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("knowledge", "Knowledge"),
                    ("problem_solving", "PROBLEM_SOLVING"),
                    ("alignment_with_job", "Alignment with Job"),
                    ("communication_skills", "Communication Skills"),
                    ("overall", "Overall"),
                ],
                max_length=25,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="InterviewFeedbackV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("knowledge", "Knowledge"),
                            ("problem_solving", "PROBLEM_SOLVING"),
                            ("alignment_with_job", "Alignment with Job"),
                            ("communication_skills", "Communication Skills"),
                            ("overall", "Overall"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="interview.interviewv2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
