# Generated by Django 4.2 on 2024-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_interviewfeedback_category_interviewfeedbackv2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewfeedback",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("knowledge", "Knowledge"),
                    ("problem_solving", "Problem Solving"),
                    ("alignment_with_job", "Alignment with Job"),
                    ("communication_skills", "Communication Skills"),
                    ("overall", "Overall"),
                ],
                max_length=25,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="interviewfeedbackv2",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("knowledge", "Knowledge"),
                    ("problem_solving", "Problem Solving"),
                    ("alignment_with_job", "Alignment with Job"),
                    ("communication_skills", "Communication Skills"),
                    ("overall", "Overall"),
                ],
                max_length=25,
                null=True,
                verbose_name="Category",
            ),
        ),
    ]
