# Generated by Django 4.2 on 2025-01-10 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_interviewv2_config"),
        ("stage", "0009_alter_stagev2_code"),
        ("feedback", "0004_alter_interviewfeedback_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewfeedbackv2",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacksV2",
                to="interview.interviewv2",
            ),
        ),
        migrations.CreateModel(
            name="InterviewFeedbackV3",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="Details"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Level"
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_feedbacksV3",
                        to="interview.interviewv2",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_feedbackV3",
                        to="stage.stagev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
