# Generated by Django 4.2 on 2024-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("in_review", "In Review"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
