# Generated by Django 4.2 on 2025-01-02 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interview", "0010_interviewv2_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("tab_inactive", "Tab Inactive")],
                        max_length=15,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 2, 16, 40, 47, 483149, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interviewv2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
