# Generated by Django 4.2 on 2025-01-04 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 4, 6, 50, 24, 583711, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Timestamp",
            ),
        ),
    ]
