# Generated by Django 4.2 on 2025-01-04 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_alter_activity_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 4, 8, 34, 40, 433536, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Timestamp",
            ),
        ),
    ]
