# Generated by Django 4.2 on 2025-01-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_alter_activity_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 5, 9, 43, 1, 895506, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Timestamp",
            ),
        ),
    ]
