# Generated by Django 4.2 on 2025-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0006_alter_activity_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="Timestamp"),
        ),
    ]
