# Generated by Django 4.2 on 2025-01-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_interviewv2_config"),
        ("activity", "0007_alter_activity_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="interview.interviewv2",
            ),
        ),
    ]
