# Generated by Django 4.2 on 2025-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0008_alter_activity_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tab_switch", "Tab Switch"),
                    ("tab_inactive", "Tab Inactive"),
                ],
                max_length=15,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
