# Generated by Django 4.2.16 on 2025-04-19 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oauthstate",
            old_name="code_challenge",
            new_name="verifier",
        ),
    ]
