# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("provider", "0001_initial"),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("INTERVIEW", "INTERVIEW"), ("FEEDBACK", "FEEDBACK")],
                        max_length=20,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "input",
                    models.TextField(blank=True, null=True, verbose_name="Input"),
                ),
                (
                    "output",
                    models.TextField(blank=True, null=True, verbose_name="Output"),
                ),
                (
                    "prompt_tokens",
                    models.BigIntegerField(default=0, verbose_name="Prompt Tokens"),
                ),
                (
                    "completion_tokens",
                    models.BigIntegerField(default=0, verbose_name="Completion Tokens"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="interview.interview",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="provider.llm",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
