# Generated by Django 4.2 on 2024-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0002_usagev2"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagev2",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Metadata"),
        ),
        migrations.AlterField(
            model_name="usage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interview", "Interview"),
                    ("feedback", "Feedback"),
                    ("review", "Review"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="usagev2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interview", "Interview"),
                    ("feedback", "Feedback"),
                    ("review", "Review"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
