# Generated by Django 4.2 on 2025-01-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_interviewv2_config"),
        ("recording", "0002_alter_videorecording_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videorecording",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_recordings",
                to="interview.interviewv2",
            ),
        ),
    ]
