

export const FEEDBACK_CREATE_REQUEST = 'FEEDBACK_CREATE_REQUEST';
export const FEEDBACK_CREATE_SUCCESS = 'FEEDBACK_CREATE_SUCCESS';
export const FEEDBACK_CREATE_FAILED = 'FEEDBACK_CREATE_FAILED';
export const FEEDBACK_CREATE_RESET = 'FEEDBACK_CREATE_RESET';