export const ACTIVITY_RETRIEVE_REQUEST = 'ACTIVITY_RETRIEVE_REQUEST';
export const ACTIVITY_RETRIEVE_SUCCESS = 'ACTIVITY_RETRIEVE_SUCCESS';
export const ACTIVITY_RETRIEVE_FAIL = 'ACTIVITY_RETRIEVE_FAIL';
export const ACTIVITY_RETRIEVE_RESET = 'ACTIVITY_RETRIEVE_RESET';