# Generated by Django 4.2 on 2025-04-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0010_alter_node_type_alter_nodev2_type"),
        ("organization", "0002_initial"),
        ("stage", "0009_alter_stagev2_code"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.AddField(
            model_name="job",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graph_jobs",
                to="graph.graphv2",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_jobs",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="stages",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="stage_jobs", to="stage.stagev2"
            ),
        ),
    ]
