# Generated by Django 4.2 on 2025-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_remove_job_company_job_graph_job_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Title"
            ),
        ),
    ]
