# Generated by Django 4.2 on 2025-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0010_alter_node_type_alter_nodev2_type"),
        ("job", "0003_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Job Id"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("job_id", "graph")},
        ),
    ]
