export const ACTIVITY_BULK_CREATE_REQUEST = 'ACTIVITY_BULK_CREATE_REQUEST';
export const ACTIVITY_BULK_CREATE_SUCCESS = 'ACTIVITY_BULK_CREATE_SUCCESS';
export const ACTIVITY_BULK_CREATE_FAILED = 'ACTIVITY_BULK_CREATE_FAILED';
export const ACTIVITY_BULK_CREATE_RESET = 'ACTIVITY_BULK_CREATE_RESET';
