#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


set +e

#python manage.py makemigrations
python manage.py migrate
#python manage.py createsuperuser --no-input
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
