# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "stage_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Stage Id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "timeout",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Timeout"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("BASE", "BASE"), ("DSA", "DSA"), ("PITCH", "PITCH")],
                        max_length=20,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "unique_together": {("stage_id", "type")},
            },
        ),
    ]
