# Generated by Django 4.2 on 2024-10-15 16:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("swe", "SWE"),
                    ("dsa", "DSA"),
                    ("pitch", "Pitch"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="StageV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "stage_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Stage Id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "timeout",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Timeout"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base", "Base"),
                            ("swe", "SWE"),
                            ("dsa", "DSA"),
                            ("pitch", "Pitch"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "unique_together": {("stage_id", "type")},
            },
        ),
    ]
