# Generated by Django 4.2 on 2024-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0002_alter_stage_type_stagev2"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagev2",
            name="module",
            field=models.CharField(
                blank=True,
                choices=[("base", "Base"), ("dsa", "DSA")],
                max_length=10,
                null=True,
                verbose_name="Module",
            ),
        ),
        migrations.AddField(
            model_name="stagev2",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Required"),
        ),
        migrations.AlterField(
            model_name="stage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("swe", "SWE"),
                    ("dsa", "DSA"),
                    ("technical", "Technical"),
                    ("behavioral", "behavioral"),
                    ("pitch", "Pitch"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="stagev2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("swe", "SWE"),
                    ("dsa", "DSA"),
                    ("technical", "Technical"),
                    ("behavioral", "behavioral"),
                    ("pitch", "Pitch"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
