# Generated by Django 4.2 on 2024-12-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0003_stagev2_module_stagev2_required_alter_stage_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("swe", "SWE"),
                    ("dsa", "DSA"),
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("coding", "Coding"),
                    ("pitch", "Pitch"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="stagev2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("swe", "SWE"),
                    ("dsa", "DSA"),
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("coding", "Coding"),
                    ("pitch", "Pitch"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
