# Generated by Django 4.2 on 2024-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0004_alter_stage_type_alter_stagev2_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagev2",
            name="submodule",
            field=models.BooleanField(default=False, verbose_name="Submodule"),
        ),
    ]
