# Generated by Django 4.2 on 2024-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0005_stagev2_submodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagev2",
            name="submodule",
            field=models.CharField(
                blank=True,
                choices=[("base", "Base"), ("dsa", "DSA")],
                max_length=10,
                null=True,
                verbose_name="Submodule",
            ),
        ),
    ]
