# Generated by Django 4.2 on 2024-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0006_alter_stagev2_submodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagev2",
            name="supervised",
            field=models.BooleanField(default=True, verbose_name="Supervised"),
        ),
    ]
