# Generated by Django 4.2 on 2025-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0007_stagev2_supervised"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagev2",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Metadata"),
        ),
    ]
