# Generated by Django 4.2 on 2025-01-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0008_stagev2_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagev2",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Code"
            ),
        ),
    ]
