# Generated by Django 4.2 on 2024-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Model"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="llm",
            unique_together={("provider", "model")},
        ),
    ]
