export const RECORDING_RETRIEVE_REQUEST = 'RECORDING_RETRIEVE_REQUEST';
export const RECORDING_RETRIEVE_SUCCESS = 'RECORDING_RETRIEVE_SUCCESS';
export const RECORDING_RETRIEVE_FAIL = 'RECORDING_RETRIEVE_FAIL';
export const RECORDING_RETRIEVE_RESET = 'RECORDING_RETRIEVE_RESET';