

export const FEEDBACK_RETRIEVE_REQUEST = 'FEEDBACK_RETRIEVE_REQUEST';
export const FEEDBACK_RETRIEVE_SUCCESS = 'FEEDBACK_RETRIEVE_SUCCESS';
export const FEEDBACK_RETRIEVE_FAIL = 'FEEDBACK_RETRIEVE_FAIL';
export const FEEDBACK_RETRIEVE_RESET = 'FEEDBACK_RETRIEVE_RESET';