// constants.js
export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST';
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS';
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL';
export const JOB_CREATE_RESET = 'JOB_CREATE_RESET';

export const JOB_RETRIEVE_REQUEST = 'JOB_RETRIEVE_REQUEST';
export const JOB_RETRIEVE_SUCCESS = 'JOB_RETRIEVE_SUCCESS';
export const JOB_RETRIEVE_FAIL = 'JOB_RETRIEVE_FAIL';
export const JOB_RETRIEVE_RESET = 'JOB_RETRIEVE_RESET';

export const JOB_UPDATE_REQUEST = 'JOB_UPDATE_REQUEST';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_FAIL = 'JOB_UPDATE_FAIL';
export const JOB_UPDATE_RESET = 'JOB_UPDATE_RESET';

export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST';
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS';
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL';
export const JOB_LIST_RESET = 'JOB_LIST_RESET';

export const JOB_FETCH_MORE_REQUEST = 'JOB_FETCH_MORE_REQUEST';
export const JOB_FETCH_MORE_SUCCESS = 'JOB_FETCH_MORE_SUCCESS';
export const JOB_FETCH_MORE_FAIL = 'JOB_FETCH_MORE_FAIL';
export const JOB_FETCH_MORE_RESET = 'JOB_FETCH_MORE_RESET';
