# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "invited",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invited at"
                    ),
                ),
                (
                    "acknowledged",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged at"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
