// constants.js
export const INTERVIEW_CREATE_REQUEST = 'INTERVIEW_CREATE_REQUEST';
export const INTERVIEW_CREATE_SUCCESS = 'INTERVIEW_CREATE_SUCCESS';
export const INTERVIEW_CREATE_FAIL = 'INTERVIEW_CREATE_FAIL';
export const INTERVIEW_CREATE_RESET = 'INTERVIEW_CREATE_RESET';

export const INTERVIEW_RETRIEVE_REQUEST = 'INTERVIEW_RETRIEVE_REQUEST';
export const INTERVIEW_RETRIEVE_SUCCESS = 'INTERVIEW_RETRIEVE_SUCCESS';
export const INTERVIEW_RETRIEVE_FAIL = 'INTERVIEW_RETRIEVE_FAIL';
export const INTERVIEW_RETRIEVE_RESET = 'INTERVIEW_RETRIEVE_RESET';

export const INTERVIEW_UPDATE_REQUEST = 'INTERVIEW_UPDATE_REQUEST';
export const INTERVIEW_UPDATE_SUCCESS = 'INTERVIEW_UPDATE_SUCCESS';
export const INTERVIEW_UPDATE_FAIL = 'INTERVIEW_UPDATE_FAIL';
export const INTERVIEW_UPDATE_RESET = 'INTERVIEW_UPDATE_RESET';

export const INTERVIEW_LIST_REQUEST = 'INTERVIEW_LIST_REQUEST';
export const INTERVIEW_LIST_SUCCESS = 'INTERVIEW_LIST_SUCCESS';
export const INTERVIEW_LIST_FAIL = 'INTERVIEW_LIST_FAIL';
export const INTERVIEW_LIST_RESET = 'INTERVIEW_LIST_RESET';

export const INTERVIEW_RESULT_DOWNLOAD_REQUEST = 'INTERVIEW_RESULT_DOWNLOAD_REQUEST';
export const INTERVIEW_RESULT_DOWNLOAD_SUCCESS = 'INTERVIEW_RESULT_DOWNLOAD_SUCCESS';
export const INTERVIEW_RESULT_DOWNLOAD_FAIL = 'INTERVIEW_RESULT_DOWNLOAD_FAIL';
export const INTERVIEW_RESULT_DOWNLOAD_RESET = 'INTERVIEW_RESULT_DOWNLOAD_RESET';

export const INTERVIEW_SUMMARY_REQUEST = 'INTERVIEW_SUMMARY_REQUEST';
export const INTERVIEW_SUMMARY_SUCCESS = 'INTERVIEW_SUMMARY_SUCCESS';
export const INTERVIEW_SUMMARY_FAIL = 'INTERVIEW_SUMMARY_FAIL';
export const INTERVIEW_SUMMARY_RESET = 'INTERVIEW_SUMMARY_RESET';

export const INTERVIEW_DAILY_SUMMARY_REQUEST = 'INTERVIEW_DAILY_SUMMARY_REQUEST';
export const INTERVIEW_DAILY_SUMMARY_SUCCESS = 'INTERVIEW_DAILY_SUMMARY_SUCCESS';
export const INTERVIEW_DAILY_SUMMARY_FAIL = 'INTERVIEW_DAILY_SUMMARY_FAIL';
export const INTERVIEW_DAILY_SUMMARY_RESET = 'INTERVIEW_DAILY_SUMMARY_RESET';

export const INTERVIEW_RECENT_UPCOMING_REQUEST = 'INTERVIEW_RECENT_UPCOMING_REQUEST';
export const INTERVIEW_RECENT_UPCOMING_SUCCESS = 'INTERVIEW_RECENT_UPCOMING_SUCCESS';
export const INTERVIEW_RECENT_UPCOMING_FAIL = 'INTERVIEW_RECENT_UPCOMING_FAIL';
export const INTERVIEW_RECENT_UPCOMING_RESET = 'INTERVIEW_RECENT_UPCOMING_RESET';

export const INTERVIEW_SCHEDULED_REQUEST = 'INTERVIEW_SCHEDULED_REQUEST';
export const INTERVIEW_SCHEDULED_SUCCESS = 'INTERVIEW_SCHEDULED_SUCCESS';
export const INTERVIEW_SCHEDULED_FAIL = 'INTERVIEW_SCHEDULED_FAIL';
export const INTERVIEW_SCHEDULED_RESET = 'INTERVIEW_SCHEDULED_RESET';
