export const SOCIAL_AUTH_REDIRECT_REQUEST = 'SOCIAL_AUTH_REDIRECT_REQUEST';
export const SOCIAL_AUTH_REDIRECT_SUCCESS = 'SOCIAL_AUTH_REDIRECT_SUCCESS';
export const SOCIAL_AUTH_REDIRECT_FAIL = 'SOCIAL_AUTH_REDIRECT_FAIL';
export const SOCIAL_AUTH_REDIRECT_RESET = 'SOCIAL_AUTH_REDIRECT_RESET';

export const SOCIAL_AUTH_CALLBACK_REQUEST = 'SOCIAL_AUTH_CALLBACK_REQUEST';
export const SOCIAL_AUTH_CALLBACK_SUCCESS = 'SOCIAL_AUTH_CALLBACK_SUCCESS';
export const SOCIAL_AUTH_CALLBACK_FAIL = 'SOCIAL_AUTH_CALLBACK_FAIL';
export const SOCIAL_AUTH_CALLBACK_RESET = 'SOCIAL_AUTH_CALLBACK_RESET';
