# Generated by Django 4.2 on 2024-10-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        # ("graph", "0004_forceedge_graphv2_force_edges"),
        ("message", "0002_sentinel_messagev2"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentinel",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node_sentinels",
                to="graph.nodev2",
            ),
        ),
    ]
