# Generated by Django 4.2 on 2024-10-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0002_alter_stage_type_stagev2"),
        ("interview", "0007_alter_interviewv2_stage"),
        ("message", "0003_sentinel_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagev2",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stage_messages_v2",
                to="stage.stagev2",
            ),
        ),
        migrations.AlterField(
            model_name="sentinel",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sentinels",
                to="interview.interviewv2",
            ),
        ),
    ]
