# Generated by Django 4.2 on 2024-10-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0007_alter_interviewv2_stage"),
        ("message", "0004_alter_messagev2_stage_alter_sentinel_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagev2",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_messages_v2",
                to="interview.interviewv2",
            ),
        ),
    ]
