# Generated by Django 4.2 on 2024-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_alter_messagev2_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagev2",
            name="internal",
            field=models.BooleanField(default=False, verbose_name="Internal"),
        ),
        migrations.AddField(
            model_name="messagev2",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="metadata"),
        ),
    ]
