# Generated by Django 4.2 on 2024-11-11 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0006_messagev2_internal_messagev2_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagev2",
            name="internal",
        ),
    ]
