# Generated by Django 4.2 on 2024-12-24 11:25

from django.db import migrations, models
import susanoo.message.models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_thought"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagev2",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=susanoo.message.models.AudioFileRename(),
                verbose_name="Audio",
            ),
        ),
    ]
