# Generated by Django 4.2 on 2024-10-15 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stage", "0002_alter_stage_type_stagev2"),
        ("provider", "0001_initial"),
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="memory_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All"),
                    ("stage", "Stage"),
                    ("isolated", "Isolated"),
                    ("None", "None"),
                ],
                max_length=10,
                null=True,
                verbose_name="Memory Level",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("io", "IO"),
                    ("worker", "Worker"),
                    ("supervisor", "Supervisor"),
                    ("terminal", "Terminal"),
                    ("sentinel", "Sentinel"),
                ],
                max_length=15,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("job", "Job"), ("PITCH", "Pitch")],
                        max_length=10,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(blank=True, null=True, verbose_name="Prompt"),
                ),
            ],
            options={
                "unique_together": {("code", "type")},
            },
        ),
        migrations.CreateModel(
            name="NodeV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("io", "IO"),
                            ("worker", "Worker"),
                            ("supervisor", "Supervisor"),
                            ("terminal", "Terminal"),
                            ("sentinel", "Sentinel"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "timeout",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Timeout"
                    ),
                ),
                (
                    "sentinel_type",
                    models.CharField(
                        blank=True,
                        choices=[("start", "Start"), ("end", "End")],
                        max_length=50,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "max_repeat",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Repeat at once"
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_nodes_v2",
                        to="provider.llm",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_config_nodes_v2",
                        to="provider.llmconfig",
                    ),
                ),
                (
                    "memory_nodes",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="node_memory",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_nodes_v2",
                        to="graph.prompt",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_nodes_v2",
                        to="stage.stagev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GraphV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("job", "Job"), ("PITCH", "Pitch")],
                        max_length=10,
                        null=True,
                        verbose_name="Graph Type",
                    ),
                ),
                (
                    "conditional_edges",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="conditional_edge_graphs_v2",
                        to="graph.conditionaledge",
                    ),
                ),
                (
                    "edges",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="edge_graphs_v2",
                        to="graph.edge",
                    ),
                ),
                (
                    "end_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_end_v2",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_start_v2",
                        to="graph.nodev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EdgeV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "end_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_end_edges_v2",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_start_edges_v2",
                        to="graph.nodev2",
                    ),
                ),
            ],
            options={
                "unique_together": {("start_node", "end_node")},
            },
        ),
        migrations.CreateModel(
            name="ConditionalEdgeV2",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Condition (Output of Start node)",
                    ),
                ),
                (
                    "end_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_node_end_edges_v2",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_node_start_edges_v2",
                        to="graph.nodev2",
                    ),
                ),
            ],
            options={
                "unique_together": {("start_node", "end_node", "condition")},
            },
        ),
    ]
