# Generated by Django 4.2 on 2024-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_alter_node_memory_level_alter_node_type_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphv2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dsa", "DSA"),
                    ("swe", "SWE"),
                    ("job", "Job"),
                    ("PITCH", "Pitch"),
                ],
                max_length=10,
                null=True,
                verbose_name="Graph Type",
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dsa", "DSA"),
                    ("swe", "SWE"),
                    ("job", "Job"),
                    ("PITCH", "Pitch"),
                ],
                max_length=10,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
