# Generated by Django 4.2 on 2024-10-17 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0003_alter_graphv2_type_alter_prompt_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForceEdge",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "end_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_end_force_edges",
                        to="graph.nodev2",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_start_force_edges",
                        to="graph.nodev2",
                    ),
                ),
            ],
            options={
                "unique_together": {("start_node", "end_node")},
            },
        ),
        migrations.AddField(
            model_name="graphv2",
            name="force_edges",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="force_edge_graphs",
                to="graph.forceedge",
            ),
        ),
    ]
