# Generated by Django 4.2 on 2024-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0005_alter_graphv2_type_alter_prompt_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphv2",
            name="edges",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="edge_graphs_v2", to="graph.edgev2"
            ),
        ),
    ]
