# Generated by Django 4.2 on 2024-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0006_alter_graphv2_edges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphv2",
            name="conditional_edges",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="conditional_edge_graphs_v2",
                to="graph.conditionaledgev2",
            ),
        ),
    ]
