# Generated by Django 4.2 on 2024-12-04 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("graph", "0007_alter_graphv2_conditional_edges"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphv2",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_graphs_v2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graphv2",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_graphs_v2",
                to="organization.organization",
            ),
        ),
    ]
