# Generated by Django 4.2 on 2024-12-09 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0008_graphv2_created_by_graphv2_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphv2",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="graphv2",
            name="organization",
        ),
    ]
