# Generated by Django 4.2 on 2024-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0009_remove_graphv2_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("io", "IO"),
                    ("worker", "Worker"),
                    ("supervisor", "Supervisor"),
                    ("autonomous", "Autonomous"),
                    ("terminal", "Terminal"),
                    ("sentinel", "Sentinel"),
                ],
                max_length=15,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="nodev2",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("io", "IO"),
                    ("worker", "Worker"),
                    ("supervisor", "Supervisor"),
                    ("autonomous", "Autonomous"),
                    ("terminal", "Terminal"),
                    ("sentinel", "Sentinel"),
                ],
                max_length=15,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
