# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import susanoo.entity.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=susanoo.entity.models.PathAndRename(
                            "interviewers/profiles/"
                        ),
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=susanoo.entity.models.PathAndRename("resumes/"),
                        verbose_name="Resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interviewer",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null="True", verbose_name="is_active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null="True",
                        verbose_name="is_deleted",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=susanoo.entity.models.PathAndRename(
                            "interviewers/profiles/"
                        ),
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Role"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
