# Generated by Django 4.2 on 2024-08-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("added_by", "email")},
        ),
    ]
