# Generated by Django 4.2 on 2024-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Metadata"),
        ),
    ]
