#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker
#exec daphne config.asgi:application -b 0.0.0.0 -p 8000 --root-path=/app
