export const STAGE_LIST_REQUEST = 'STAGE_LIST_REQUEST';
export const STAGE_LIST_SUCCESS = 'STAGE_LIST_SUCCESS';
export const STAGE_LIST_FAIL = 'STAGE_LIST_FAIL';
export const STAGE_LIST_RESET = 'STAGE_LIST_RESET';
